version: "3.6"
services:
  web:
    build:
        context: .
        dockerfile: CQRS vs CRUD/Dockerfile
    image: web
    entrypoint: []
    command: sh -c "dockerize -wait tcp://mssql:1433 -timeout 300s -wait-retry-interval 5s dotnet 'CQRS vs CRUD.dll'"
    ports:
      - "5001:443"
      - "5000:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
    depends_on:
      - mssql
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "P@assw0rd"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"