version: "3.6"
services:
  web:
    build:
        context: .
        dockerfile: CQRS vs CRUD/Dockerfile.Build
    image: web
    ports:
      - "5001:443"
      - "5000:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"