FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY ["./CQRS vs CRUD/CQRS vs CRUD.csproj", "./"]
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN ls
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "CQRS vs CRUD.dll"]